### PR TITLE
Update istio graduation status

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Please make sure that you follow instructions from [CONTRIBUTING](https://github.com/cncf/devstats/blob/master/CONTRIBUTING.md)

Specially:
- Check if all tests pass, see [TESTING](https://github.com/cncf/devstats/blob/master/TESTING.md) for deatils.
- Make sure you've added test coverage for new features/metrics.
- Make sure you have updated documentation.
- If you added a new metric, please make sure you have been following instructions about [adding new metric](https://github.com/cncf/devstats/blob/master/METRICS.md).

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm - this requires more changes, but I will cover this on Friday.
Thanks!
Please also make sure that cncf/landscape is updated (if it isn't yet).

**Comment by hzxuzhonghu** [comment]
Seems landscape it is updated

**Comment by lukaszgryglicki** [comment]
OK, great, other DevStats updated will be there on Friday.

**Comment by lukaszgryglicki** [comment]
DevStats instance updated.

**Comment by hzxuzhonghu** [comment]
Thank you @lukaszgryglicki

**Pull request merged**
