### PR TITLE
grafana/img/flatcar: Add correct logos

### PR DESCRIPTION
**Pull request by t-lo**
This change adds the actual Flatcar Container Linux project logos to devstats (see e.g. https://www.flatcar.org/ for examples of these logos).

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
I could merge this, but DevStats fetches those from `cncf/artwork` - can you point me toi where they are in that repo? I'll update scripts to fetch from there - using manually specified files via PR will work just once, and next time images are built this would be overwritten.

**Comment by t-lo** [comment]
Gotcha, thanks! I was not aware of cncf/artwork, will have a look there.

**Comment by lukaszgryglicki** [comment]
Ideally just provide the same images there. TY.

**Comment by lukaszgryglicki** [comment]
OK, so I'm closing this instead.

**Pull request closed without merging**
